# Generated by Django 4.0.4 on 2022-06-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_name_scope_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
