# Generated by Django 4.0.4 on 2022-06-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_tag_scope_tag_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag_name',
            new_name='name',
        ),
    ]
