# Generated by Django 4.0.4 on 2022-06-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_name_scope_tag_alter_articlescope_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='article_scope',
            field=models.ManyToManyField(related_name='tag', through='articles.ArticleScope', to='articles.article'),
        ),
    ]
