# Generated by Django 4.0.4 on 2022-06-16 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_tag_scope_name_alter_articlescope_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scope', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='article_scope',
            field=models.ManyToManyField(through='articles.ArticleScope', to='articles.article'),
        ),
    ]
