# Generated by Django 4.0.4 on 2022-06-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articlescope_article_alter_articlescope_scope'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='name',
            new_name='tag',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='Статья'),
        ),
    ]
