# Generated by Django 4.0.4 on 2022-06-16 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_alter_articlescope_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tag',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='articlescope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='articles.scope', verbose_name='Раздел'),
        ),
    ]
